#!/bin/bash

set -e
set -o nounset

export T_DATA_FILE=$(t path) # this gets the path from my wrapper for 't'.
BUILD=target/release/t
VALIDATE_COUNT=20

echo -n lines to parse:
wc -l "${T_DATA_FILE}"

(set -x; cargo build --release)

getsum() {
  shasum "$1" | awk '{print $1}'
}

mkdir -p benches
new_shasum="$(getsum "$BUILD")"
build_is_new=true
for f in benches/t-*; do
  if [ "$(getsum "$f")" = "$new_shasum" ]; then
    echo New build is identical to $f.
    build_is_new=false
  fi
done
if $build_is_new; then
  cp "$BUILD" benches/t-$(date +%s)-$(git rev-parse HEAD | cut -c1-10)
fi

set --
for x in benches/t-*; do
  set -- "$@" "${x} validate -c ${VALIDATE_COUNT}"
done
(set -x; hyperfine -w 1 "$@")
