#!/bin/bash

set -e
set -o nounset

image=t-dev

docker build --rm \
  --build-arg USERNAME=$USER \
  --build-arg USER_UID=$(id -u) \
  --build-arg USER_GID=$(id -g) \
  -t $image \
  images/dev

r() {
  docker run -it --rm \
    -u $(id -u):$(id -g) \
    -w /work/rust \
    -v $(pwd):/work \
    -v ${image}-cargo:/usr/local/cargo \
    -p 8880:8880 \
    $image \
    "$@"
}

r /bin/bash
