#!/bin/bash

set -e
set -o nounset

ROOT=$(cd "$(dirname "$0")/.."; pwd -P)
T_RUST="${ROOT}/target/release/t"

t_ruby() {
  cd "$ROOT"
  unset RBENV_VERSION
  exec bin/t "$@"
}

if [ ! -x "$T_RUST" ] || [ -n "${FORCE_RUBY:-}" ]; then
  t_ruby "$@"
fi

if [ $# -gt 0 ]; then
  case "$1" in
    # todo - fill in commands that the rust version doesn't do yet.
    todo)
      t_ruby "$@" ;;
  esac
fi

exec "$T_RUST" "$@"
